name: lego_3_views
subset:
  view_count: 3
  output_dir: data/splits/3_views
  selection:
    indices: [0, 34, 68]
training:
  args:
    iterations: 15000
    test_iterations: [7000, 15000]
    save_iterations: [7000, 15000]
    optimizer_type: sparse_adam
render:
  iterations: [15000]
  args:
    skip_train: true
    skip_test: false
    quiet: true
metrics:
  subset_label: 3_views
